version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: protobuf
    versions:
    - 3.14.0
    - 3.15.0
    - 3.15.1
    - 3.15.2
    - 3.15.3
    - 3.15.4
    - 3.15.5
    - 3.15.6
    - 3.15.7
  - dependency-name: fonttools[lxml,ufo,unicode]
    versions:
    - 4.19.1
    - 4.20.0
    - 4.21.1
    - 4.22.0
  - dependency-name: defcon
    versions:
    - 0.8.0
  - dependency-name: pip-api
    versions:
    - 0.0.18
    - 0.0.19
  - dependency-name: lxml
    versions:
    - 4.6.2
